# Generated by Django 3.1.7 on 2021-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField(default=False)),
                ('xray', models.IntegerField()),
                ('c_react', models.BooleanField(default=False)),
                ('comp', models.IntegerField()),
                ('bmi', models.BooleanField(default=False)),
                ('sinovit', models.BooleanField(default=False)),
                ('soe', models.BooleanField(default=False)),
            ],
        ),
    ]
