# Generated by Django 3.1.7 on 2021-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='c_react',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sinovit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='soe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='xray',
            field=models.IntegerField(null=True),
        ),
    ]
