# Generated by Django 3.1.7 on 2021-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210505_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='echt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
