# Generated by Django 3.1.7 on 2021-05-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_echt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='soe',
        ),
    ]
