# Generated by Django 3.1.7 on 2021-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210517_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='compc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comp',
            field=models.IntegerField(null=True),
        ),
    ]
